name = "zyra"
compatibility_dname = "zyrashop"
main = "src/index.js"
compatibility_date = "2023-12-01"

[assets]
directory = "./public"

[[d1_databases]]
binding = "DB"
database_name = "zyra"
database_id = "541b9b3d-0763-4eda-bb61-51c31b2d1d5e"
